spring.application.name=dark
spring.datasource.url=jdbc:mysql://localhost:3306/dbb
spring.datasource.username=root
spring.datasource.password=Suja@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8086

